name: CD - Deploy to Staging

on:
  push:
    branches:
      - testing
    paths:
      - 'backend/**'
      - '.github/workflows/**'

env:
  STAGING_NAMESPACE: staging-latest

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout testing branch
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Create staging namespace
        run: |
          kubectl create namespace ${{ env.STAGING_NAMESPACE }} || true

      - name: Deploy everything
        run: |
          cd k8s/
          kubectl apply -f product-db.yaml -n ${{ env.STAGING_NAMESPACE }}
          kubectl apply -f order-db.yaml -n ${{ env.STAGING_NAMESPACE }}
          kubectl apply -f product-service.yaml -n ${{ env.STAGING_NAMESPACE }}
          kubectl apply -f order-service.yaml -n ${{ env.STAGING_NAMESPACE }}

      - name: Logout
        run: az logout
        if: always()